trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  VITE_SUPABASE_URL: "https://mcpzbvznxmkbvaeajwua.supabase.co/"
  NEXT_PUBLIC_API_URL: "http://localhost:8000/"

stages:
  - stage: Frontend
    displayName: "Frontend Setup & Build"
    jobs:
      - job: frontend_build
        displayName: "Install & Build Frontend"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: "Use Node.js 20"

          - script: |
              cd frontend
              npm ci
              npm install tailwindcss @tailwindcss/vite
              npm install -D @types/node
              npm install @supabase/supabase-js
              npm install -D vitest @testing-library/react @testing-library/jest-dom @testing-library/user-event jsdom
              npx shadcn@latest init
              npx shadcn@latest add navigation-menu
              npm run build
            displayName: "Install frontend dependencies and build"

          - script: |
              cd frontend
              npm run test
            displayName: "Run frontend tests"

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/vitest-results.xml'
              testRunTitle: 'Frontend Tests'
            condition: succeededOrFailed()
            displayName: "Publish Frontend Test Results"

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'frontend/dist'
              artifactName: 'frontend_dist'
            displayName: "Publish Frontend Build"

  - stage: Backend
    displayName: "Backend Setup & Run"
    dependsOn: Frontend
    jobs:
      - job: backend_setup
        displayName: "Install & Run Backend"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
            displayName: "Use Python 3.11"

          - script: |
              cd backend
              python -m venv .venv
              source .venv/bin/activate
              python -m pip install --upgrade pip
              pip install supabase fastapi "uvicorn[standard]" httpx python-dotenv

              cd tmdb-api
              python -m venv .venv
              source .venv/bin/activate
              pip install supabase fastapi "uvicorn[standard]" httpx python-dotenv
            displayName: "Install backend dependencies"
#IMPROTANT, we may need to change is so that it boots in the tmdb-api folder first to populate the movies, then boot the main backend, but if this works then keep it as is.
          - script: |
              cd backend
              source .venv/bin/activate
              nohup uvicorn main:app --reload --port 8000 &
            displayName: "Run Backend API"
#Tests for Friends and Group Members, may need some touches to fully work
          - script: |
              cd backend
              pip install -r requirements.txt
              pip install pytest pytest-asyncio httpx
              pytest -v tests/test_api.py --junitxml=pytest-results.xml
            displayName: "Run Friends & Groups API Tests"
            continueOnError: false

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/pytest-results.xml'
              testRunTitle: 'Friends & Groups API Tests'

