trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: ubuntu-latest

variables:
  - group: SupabaseSecrets      # <-- must match the group name exactly
  - name: VITE_SUPABASE_URL
    value: "https://mcpzbvznxmkbvaeajwua.supabase.co/"
  - name: NEXT_PUBLIC_API_URL
    value: "http://localhost:8000/"

stages:
  - stage: Frontend
    displayName: "Frontend Setup & Build"
    jobs:
      - job: frontend_build
        steps:
          - task: NodeTool@0
            inputs: { versionSpec: '20.x' }
          - script: |
              set -e
              cd frontend
              npm ci
              npm install tailwindcss @tailwindcss/vite
              npm install -D @types/node
              npm install @supabase/supabase-js
              npx shadcn@latest init -y || true
              npx shadcn@latest add navigation-menu || true
              npm run build
            displayName: "Install frontend dependencies and build"
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'frontend/dist'
              artifactName: 'frontend_dist'

  - stage: Backend
    displayName: "Backend: Install & Test"
    dependsOn: Frontend
    jobs:
      - job: backend_tests
        steps:
          - task: UsePythonVersion@0
            inputs: { versionSpec: '3.11' }
          - script: |
              set -e
              python -m venv .venv
              source .venv/bin/activate
              python -m pip install --upgrade pip
              if [ -f backend/requirements.txt ]; then
                pip install -r backend/requirements.txt
              else
                pip install fastapi "uvicorn[standard]" httpx python-dotenv supabase pytest pytest-cov anyio
              fi
            displayName: "Install backend dependencies"
          - script: |
              set -e
              source .venv/bin/activate
              cd backend
              pytest -vv tests/test_privacy.py
            displayName: "Run backend tests"
            env:
              SUPABASE_URL: $(SUPABASE_URL)
              SUPABASE_SERVICE_ROLE_KEY: $(SUPABASE_SERVICE_ROLE_KEY)
              TEST_AUTH_USER_ID: $(TEST_AUTH_USER_ID)
