trigger:
  branches:
    include:
      - main
      # - dev --maybe later

pool:
  vmImage: 'ubuntu-latest'

steps:
#Frontend
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Set up Node.js'

- script: |
    cd frontend
    npm install
    npm install tailwindcss @tailwindcss/vite
    npm install -D @types/node
    npm install react-router
    npx shadcn@latest init -y
    npx shadcn@latest add navigation-menu
    npm run build
  displayName: 'Install Frontend and Build'

#Backend
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
  displayName: 'Set up Python'

- script: |
    cd backend
    python -m venv .venv
    source .venv/bin/activate
    python -m pip install --upgrade pip
    python -m pip install fastapi "uvicorn[standard]" httpx python-dotenv
  displayName: 'Install Backend (No Build)'

  #Eventually will need to look into also running the backend once we figure that out