trigger:
- search-and-view-movies
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11.9'
  nodeVersion: '24.7.0'

jobs:
- job: TestBackend
  displayName: 'Test FastAPI Backend'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest pytest-asyncio httpx
    displayName: 'Install Python dependencies'
    workingDirectory: '$(System.DefaultWorkingDirectory)/backend/tmdb-api'

  - script: |
      python -m pytest -v
    displayName: 'Run backend tests'
    workingDirectory: '$(System.DefaultWorkingDirectory)/backend/tmdb-api'
    condition: succeededOrFailed()